version: '3'

networks:
  conectra:
    name: 'conectra'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUN_SCRIPTS=1
      - SKIP_CHOWN=true
      - PHP_MEM_LIMIT=256
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    networks: 
      - conectra

  postgres:
    image: postgres:9.6-alpine
    hostname: postgres.conectra
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/postgres:/var/lib/postgresql/data
    labels:
      - traefik.enabled=false
    networks: 
      - conectra
